### PR TITLE
to do list added

### PR DESCRIPTION
**Pull request by pr0x7**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by anjali1102** [comment]
show deployed link for index file (u can use netlify or other)
and put your project screenshot over (drag and drop for image)
image

**Comment by pr0x7** [comment]
What do you mean? Plz explain

**Comment by anjali1102** [comment]
deploy means making project online available to everyone....
as you have made index.html projects, so you can host them and send me deployed link
https://www.youtube.com/watch?v=CAZb4SiWLIw

**Comment by pr0x7** [comment]
[prox-todo-list.netlify.app](https://prox-todo-list.netlify.app/)

**Comment by pr0x7** [comment]
Screen Shot 2022-10-03 at 2 59 36 PM

**Comment by anjali1102** [comment]
> [prox-todo-list.netlify.app](https://prox-todo-list.netlify.app/)

https://prox-todo-list.netlify.app/to_do_list.html   @pr0x7

**Pull request merged**
