### PR TITLE
Disk Scheduling Algorithms Simulation

### PR DESCRIPTION
**Pull request by manavukani**
# Description

-- This project is intended for simulating how the number of file requests affects the performance of these algorithms.
-- An interactive graph is used to visualize these algorithms using CanvasJs, a JavaScript library.
-- Languages used: HTML, CSS, JavaScript

Link for the project: https://disk-scheduling-algorithm-simulation.netlify.app/

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

## Screenshots
image

image

### CODE REVIEW

**Comment by manavukani** [comment]
Added in the description

**Comment by anjali1102** [comment]
deployed link, to see functioning

**Comment by manavukani** [comment]
I'm new to open source, so how do i delete a committed change??

**Comment by manavukani** [comment]
> deployed link, to see functioning

https://disk-scheduling-algorithm-simulation.netlify.app/

**Pull request merged**
