### PR TITLE
Tribute page of APJ Abdul Kalam Fix: #240

### PR DESCRIPTION
**Pull request by Akshaysrajan**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(240)

# Checklist:

- [✅ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Akshaysrajan** [comment]
deployed link https://akshaysrajan.github.io/Hacktober2022/Tribute_page/ 
image was working well while development.

**Comment by Akshaysrajan** [comment]
@anjali1102 mam, can i know how to resolve this
image

**Comment by anjali1102** [comment]
again check 
it should show waiting

**Comment by Akshaysrajan** [comment]
okay mam thanks no its working

**Comment by anjali1102** [comment]
it will update, other people are having waiting

**Pull request merged**
