### PR TITLE
Yt clone

### PR DESCRIPTION
**Pull request by ayushwritescode**
Fixes (#380)[https://github.com/anjali1102/Hacktober2022/issues/380]

#380 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by anjali1102** [comment]
image

merge conflicts
 `delete wordle-clone` and `readme file added`
 and push changes

**Comment by ayushwritescode** [comment]
if I just delete the readme file will it be okay ?
image

**Comment by ayushwritescode** [comment]
I am going with git reset command :(

**Comment by ayushwritescode** [comment]
closing this pull request because of merge conflicts I will come up with another pr

**Pull request closed without merging**
